# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.11.0
_src_path: gh:oca/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: false
github_check_license: true
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_version: 14.0
org_name: Odoo Community Association (OCA)
org_slug: https://github.com/OCA/operating-unit
rebel_module_groups: []
repo_description: Operating Units Addons
repo_name: operating-unit
repo_slug: operating-unit
repo_website: https://github.com/OCA/operating-unit
travis_apt_packages: []
travis_apt_sources: []
